### ISSUE TITLE
Package requires UniTask to compile

### ISSUE THREAD

**Issue by VirtualMaestro** [mygamedevtools/scene-loader#29]
Hey and thank you for the lib!
I wanted to add the lib via git URL, so  these steps
- Select Add package from git URL....
- Paste https://github.com/mygamedevtools/scene-loader.git#upm

and I got an issue about some namespace.
![image](https://github.com/mygamedevtools/scene-loader/assets/426870/fa5eec76-79a1-4701-bef1-72dc2995c5a4)

Unity version 2023.2.12f1

Thank you in advance!

**Comment by thatjoaoguy** [comment]
Thanks for reporting! I'll take a closer look, but looks like the issue is not related to the package being imported via git, but with missing preprocessing directives on a class. If that's the case, I'll release a fix later today.

**Comment by thatjoaoguy** [comment]
The fix was simpler, the UniTask namespace was not used in that class but was required by the `using` statements. A patch version should land soon.
