### ISSUE TITLE
Can we add support for CancellationToken for async SceneLoaders

### ISSUE THREAD

**Issue by HamzaRino** [mygamedevtools/scene-loader#4]
Is this even possible or recommended with Unity's `AsyncOperation` / `SceneManager.LoadSceneAsync`?

**Comment by thatjoaoguy** [comment]
Hey @HamzaRino, thanks for your suggestion! I don't think it's possible to **cancel** a scene load operation, as the current state of `Unity's Scene Management` or `Addressable Scene Management`. However, if you think there's a benefit for including `CancellationToken` values in the Scene Loaders that might improve the experience in other scenarios, I'd like to know more about it.

My initial thought was that, considering that we cannot properly cancel a scene load operation (as far as I've researched), I wouldn't include the `CancellationToken`. One thing that could be done, would be to disable the `allowSceneActivation` and unload the scene if the operation is cancelled. What do you think about this? Did you have a use case in mind?

**Comment by HamzaRino** [comment]
Hi @joaoborks, thanks a lot for your prompt reply and for confirming that indeed we cannot cancel AsyncOperation including SceneManager.LoadSceneAsync. And using UniTask's WithCancellation is not recommended for the reasons mentioned [here](https://github.com/Cysharp/UniTask#playerloop:~:text=In%20UniTask%2C%20await%20directly%20uses%20native%20timing%2C%20while%20WithCancellation%20and%20ToUniTask%20use%20specified%20timing.%20This%20is%20usually%20not%20a%20particular%20problem%2C%20but%20with%20LoadSceneAsync%2C%20it%20causes%20a%20different%20order%20of%20Start%20and%20continuation%20after%20await.%20So%20it%20is%20recommended%20not%20to%20use%20LoadSceneAsync.ToUniTask.).
And yes I thought about the abort or revert as a fake cancellation by disabling activation and unloading the additive.
I have a similar use case where I can cancel some scene loading validation and preloading async methods that happen before the actual loading.
But I think it does not make sense to add this if it's not supported and it will only be confusing.
Unity 2022 brings [MonoBehaviour.destroyCancellationToken](https://docs.unity3d.com/2022.2/Documentation/ScriptReference/MonoBehaviour-destroyCancellationToken.html) maybe it will bring more [in the future](https://blog.unity.com/technology/unity-and-net-whats-next#:~:text=Improving%20the%20async/await%20programming%20model.%20Async/await%20is%20a%20fundamental%20programming%20approach%20to%20writing%20gameplay%20code%20that%20must%20wait%20for%20an%20asynchronous%20operation%20to%20complete%20without%20blocking%20the%20engine%20mainloop.%C2%A0).

Thanks again for your reply and this awesome package.
