### ISSUE TITLE
ArgumentException: Attempted to get an ISceneData through an invalid or unloaded scene.

### ISSUE THREAD

**Issue by VirtualMaestro** [mygamedevtools/scene-loader#42]
Hey João,
The bug I posted is now fixed and works fine. Thanks. 
Another issue, I think. The code is super simple. I use 'new AdvancedSceneManager(addLoadedScenes: true);'
So, I have a Loader scene that is the first scene and the only scene with the only one Monobehaviour script.
```csharp
    public class MonoBeh : MonoBehaviour
    {
        private void Awake()
        {
             ISceneManager sceneManager = new AdvancedSceneManager(true);
             ISceneLoader asyncSceneLoader = new SceneLoaderAsync(sceneManager);
        }
    }

```
![image](https://github.com/user-attachments/assets/3039fc22-84c4-4c12-b134-b5dcb792764c)

**Comment by thatjoaoguy** [comment]
Hello again @VirtualMaestro! Thanks for reporting another issue.

I believe this may be caused by calling `new AdvancedSceneManager(true)` on the first scene during `Awake()`. I assume (couldn't find a solid reference) that `Awake()` is executed **before** the scene finishes loading.

Here's what's being called:
```cs
public SceneDataStandard(Scene loadedScene)
{
    if (!loadedScene.IsValid() || !loadedScene.isLoaded)
    {
        throw new ArgumentException($"Cannot create a {nameof(SceneDataStandard)} with an invalid or not loaded scene: {loadedScene.name} ({loadedScene.handle})");
    }

    _loadSceneInfo = new LoadSceneInfoScene(loadedScene);
    _sceneReference = loadedScene;
    _asyncSceneOperation = default;
}
```
> Full execution:
> 1. [new AdvancedSceneManager(true)](https://github.com/mygamedevtools/scene-loader/blob/9855e6b3e6e81a16a7188b6a5edd55a75ccb87d5/Packages/com.mygamedevtools.scene-loader/Runtime/AdvancedSceneManager.cs#L43)
> 2. [_loadedScenes.Add(SceneDataBuilder.BuildFromScene(scene));](https://github.com/mygamedevtools/scene-loader/blob/9855e6b3e6e81a16a7188b6a5edd55a75ccb87d5/Packages/com.mygamedevtools.scene-loader/Runtime/AdvancedSceneManager.cs#L56)
> 3. [new SceneDataStandard(scene)](https://github.com/mygamedevtools/scene-loader/blob/9855e6b3e6e81a16a7188b6a5edd55a75ccb87d5/Packages/com.mygamedevtools.scene-loader/Runtime/Utilities/SceneDataBuilder.cs#L30)
> 4. [if (!loadedScene.IsValid() || !loadedScene.isLoaded)](https://github.com/mygamedevtools/scene-loader/blob/9855e6b3e6e81a16a7188b6a5edd55a75ccb87d5/Packages/com.mygamedevtools.scene-loader/Runtime/Structs/SceneDataStandard.cs#L45)

That means it's probably failing the `loadedScene.isLoaded` check, since it's a valid scene in the given context.

### Possible workaround
Try moving that call to `Start()` instead to see if it works.

### Solving the issue
This issue got me thinking: considering you cannot do this in `Awake()`, how can it prevent it?

One solution would be to identify that even though we're passing `true` to that argument, no scene is being added to the loaded scene list. Then it emits a log message saying you're probably doing this on `Awake` and should defer it to `Start`. That is, assuming that moving the construction of the `AdvancedSceneManager` to `Start` **does** fix the issue.

What do you think about this?

**Comment by VirtualMaestro** [comment]
Yeah, you are right; it is because of the Awake phase, where the scene can be in the state of not fully loaded.
To add the proper message would definitely help. Thank you)

**Comment by VirtualMaestro** [comment]
There is another issue.
Almost the same code, but the it works by the following scenario.
- Loader scene is loaded;
- Than it loads another scene (Main);
- The Loader scene is unloading; - and at this step an issue and the scene can't be unloaded.

"Unable to get an ISceneData with the load scene info Scene with name/path 'Assets/Client/Scenes/Loader.unity'.
UnityEngine.Debug:LogWarning (object)
MyGameDevTools.SceneLoading.SceneDataUtilities:TryGetSceneDataByLoadSceneInfo (MyGameDevTools.SceneLoading.ILoadSceneInfo,System.Collections.Generic.ICollection`1<MyGameDevTools.SceneLoading.ISceneData>,MyGameDevTools.SceneLoading.ISceneData&) (at ./Library/PackageCache/com.mygamedevtools.scene-loader@38b9126553/Runtime/Utilities/SceneDataUtilities.cs:177)"

```csharp
private static readonly ILoadSceneInfo LoaderSceneInfo = new LoadSceneInfoName("Assets/Client/Scenes/Loader.unity");
private static readonly ILoadSceneInfo MainSceneInfo = new LoadSceneInfoName("Assets/Client/Scenes/Main.unity");

private ISceneManager _sceneManager;
private ISceneLoader _asyncSceneLoader;
	
private void Start()
{
	_sceneManager = new AdvancedSceneManager(true);
	_asyncSceneLoader = new SceneLoaderAsync(_sceneManager);
	
	_asyncSceneLoader.Manager.SceneLoaded += _OnSceneLoaded;
	_asyncSceneLoader.LoadScene(MainSceneInfo, true);
}

private void _OnSceneLoaded(Scene scene)
{
	_asyncSceneLoader.UnloadScene(LoaderSceneInfo);	// FIXME: The scene can't be unloaded
}
```

**Comment by thatjoaoguy** [comment]
I think I know what's going on with this new error.

You have defined your `LoaderSceneInfo` to be a `LoadSceneInfoName` with the scene's path. However, when creating the `AdvancedSceneManager` with `addLoadedScenes: true`, it internally links loaded scenes with `LoadSceneInfoScene` instead.

Then, when trying to unload using a different `ILoadSceneInfo` reference it fails to match.

I can offer a few suggestions to fix this:
1. Do a scene transition
    - Instead of loading the main scene and unloading the loader scene manually, you can transition from the loader to the main scene and let the scene manager handle the complexities. Since `3.x` you can transition even if you only have one scene loaded. Simply call `_asyncSceneLoader.TransitionToScene(MainSceneInfo)` with no intermediate scene.
2. Unload via a `LoadSceneInfoScene`
    - After creating the scene manager, you can get the loader scene info via `new LoadSceneInfoScene(_sceneManager.GetActiveScene())`

It makes sense for a user's point of view to be able to unload a scene from its path, even though it was never loaded through that, and it works with the Unity Scene Manager as well. Maybe this is a feature that needs to be added as well.

Let me know if you are able to fix the issue with my suggestions.

**Comment by VirtualMaestro** [comment]
Yes, the _asyncSceneLoader.TransitionToScene(MainSceneInfo) does the thing.
Thank you)

**Comment by thatjoaoguy** [comment]
Here's a list of things that I consider relevant for mitigating this issue:

1. Improve the log message for creating an `AdvancedSceneManager(addLoadedScenes: true)` on `Awake()`
2. Add documentation regarding this restriction
3. Add a Troubleshooting section to the documentation
4. Investigate possibility to _cross-reference_ `ILoadSceneInfo` to unload scenes
    - For example, to unload a scene that was linked through `LoadSceneInfoScene` with a `LoadSceneInfoName`
    
I'll be working on 1~3 right away and study a solution for 4.

**Comment by thatjoaoguy** [comment]
I've created the issue #44 to reflect the 4th step of my list.
