### ISSUE TITLE
TransitionToScene (and variants) only unload the current active scene.

### ISSUE THREAD

**Issue by Clozent** [mygamedevtools/scene-loader#45]
When using `TransitionToSceneAsync()` to transition between scenes, I expected that the scene loader would unload all scenes under it's management when transitioning. Instead, no scene was unloaded at all, because I didn't make the scene I wished to unload the active scene.

This is a problem.

Unloading only the active scene is extremely limiting, as there is currently no way to transition from:

1. A scene that is not the active scene
2. A collection of scenes

What I propose is that `ISceneLoader.TransitionToScene()` and `ISceneLoader.TransitionToScenes()` would accept a scene or an array of scenes to unload, and that the implementations of these methods in `SceneLoaderAsync`, `SceneLoaderCoroutine`, and `SceneLoaderUniTask` would unload all managed scenes by default.

I know this will break backwards compatibility, but it doesn't seem like much of a problem, seeing as this package already broke some backwards compatibility in the past.

**Comment by thatjoaoguy** [comment]
Hi @Clozent, thanks for your report.

I agree with you, simply unloading the active scene only covers a simple use case. It does not need to break compatibility though, we can just add new method alternatives for scene transition, such as:

1. Passing scenes to be unloaded
  ```cs
  void TransitionToScenesAsync(ILoadSceneInfo[] targetScenes, int setIndexActive, ILoadSceneInfo[] unloadScenes, ILoadSceneInfo intermediateSceneReference = null)
  ```
2. Option to unload all managed scenes
  ```cs
  void TransitionToScenesAsync(ILoadSceneInfo[] targetScenes, int setIndexActive, bool unloadAllScenes, ILoadSceneInfo intermediateSceneReference = null)
  ```
  
With the new methods, you'd have three options for transition:
1. Transition and unload the active scene (current implementation)
2. Transition and unload a group of scenes
3. Transition and unload all other managed scenes

What do you think? If you agree, I'll start working on it right away.

**Comment by Clozent** [comment]
Hi, overall, I think these new methods are a good way to solve this problem.

One thing is bugging me, though: the method `void TransitionToScenesAsync(ILoadSceneInfo[] targetScenes, int setIndexActive, bool unloadAllScenes, ILoadSceneInfo intermediateSceneReference = null)` changes it's behavior depending on a boolean (`unloadAllScenes`, in this case), which is, from my understanding, something a method should avoid.

Instead, I think it would be best to make the behavior a separate method, such as `TransitionToScenesUnloadAll(...)` (I don't think this is a good name for it, but I can't come up with anything better).

**Comment by thatjoaoguy** [comment]
You're right, it'd be better to introduce a new method for unloading all scenes.

So to summarize, two new methods will be added:

1. `TransitionToScenesFromScenes` - unloads multiple provided scenes
2. `TransitionToScenesFromAll` - unloads all managed scenes

Not so sure about the names yet, but that's the scope. I'll start working on it today.

**Comment by thatjoaoguy** [comment]
Adding a development note for my future self:

Check whether including #44 improves the experience when using `TransitionToScenesFromScenes`.
